version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - mynetwork

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mynetwork

networks:
  mynetwork:

